CREATE TABLE [TBL_QUESTIONS]
(
QUESTION_ID INT IDENTITY NOT NULL,
QUESTIONS NVARCHAR(255) NOT NULL,
CORRECT_ANSWER_1 NVARCHAR(255) NOT NULL,
ANSWER_2 NVARCHAR(255) NOT NULL,
ANSWER_3 NVARCHAR(255) NOT NULL,
ANSWER_4 NVARCHAR(255) NOT NULL,
CONSTRAINT PK_TBL_QUESTIONS PRIMARY KEY (QUESTION_ID)
)