CREATE TABLE [USER]
(
[USER_ID] INT IDENTITY NOT NULL,
EMAIL NVARCHAR(255),
[PASSWORD] BINARY(60),
USERNAME NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CS_AS,
DATE_OF_BIRTH DATE,
CONSTRAINT PK_USER_USER_ID PRIMARY KEY ([USER_ID])
)